name: Regular Analyze
- description: "Analyze Every 5 Minutes"
  schedule: every 5 minutes
  
env:
  IMAGE_TEST: task2_test
  
jobs:
  Analyze:
    name: Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Scan Image Before Push
      - name: Scan Image
        uses: ISID/build-and-scan-image@main
        with:
          tag: $IMAGE:test
          path: .
          trivy-severity: CRITICAL
  
